# Generated by Django 6.0.3 on 2026-04-03 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONSULTA', 'Consulta General'), ('DESPARASITACION', 'Desparasitacion'), ('GROOMING', 'Grooming'), ('LABORATORIO', 'Laboratorio'), ('CIRUGIA', 'Cirugia Menor'), ('HOSPITALIZACION', 'Hospitalizacion'), ('HOSPEDAJE', 'Hospedaje')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='precio en cordobas', max_digits=10)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='core.sucursal')),
            ],
        ),
    ]
