# Generated by Django 6.0.3 on 2026-04-04 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_propietario_mascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('analgesicos_antiflamatorios', 'Analgesicos y antiflamatorios'), ('antibioticos', 'Antibioticos'), ('antiparasitarios_internos', 'Antiparasitarios externos'), ('vacunas', 'Vacunas'), ('antiemeticos_digestivos', 'Antiemeticos y digestivos'), ('sueros_soluciones', 'sueros y soluciones'), ('anticonvulsivos', 'Anticonvulsivos'), ('corticoides', 'Corticoides'), ('anestesicos_sedantes', 'Anestesicos y sedantes'), ('antisepticos_topicos', 'Antisepticos y topicos'), ('hormonas_endocrinos', 'hormonas y tratamientos endocrinos'), ('oftalmicos_oticos', 'oftalmicos y oticos'), ('productos_dermatologicos', 'productos dermatologicos'), ('eutanasia_emergencias', 'Eutanasia y emergencias')], max_length=60)),
                ('descripcion', models.TextField()),
                ('stock', models.PositiveBigIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('Sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farmacos', to='core.sucursal')),
            ],
            options={
                'ordering': ['Sucursal__nombre', 'categoria', 'nombre'],
                'unique_together': {('Sucursal', 'nombre')},
            },
        ),
    ]
