# Generated by Django 6.0.3 on 2026-04-06 04:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_farmaco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitada', models.DateField(default=django.utils.timezone.now)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('duracion', models.IntegerField(default=30)),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('vacunacion', 'Vacunacion'), ('cancelada', 'Cancelada'), ('cirugia', 'Cirugia')], default='consulta', max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('programada', 'Programada'), ('atendida', 'Atendida'), ('cancelada', 'cancelada')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mascota')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='core.sucursal')),
                ('veterinario', models.ForeignKey(limit_choices_to={'rol': 'VET'}, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CitaFarmaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('registrado', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administraciones_farmacos', to='core.cita')),
                ('farmaco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administraciones', to='core.farmaco')),
            ],
            options={
                'ordering': ['farmaco__nombre'],
                'unique_together': {('cita', 'farmaco')},
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='farmacos_utilizados',
            field=models.ManyToManyField(blank=True, help_text='Medicamentos del inventario utilizados durante la atencion.', related_name='citas_utilizadas', through='core.CitaFarmaco', through_fields=('cita', 'farmaco'), to='core.farmaco'),
        ),
    ]
